NAME=philo
CC=cc
CFLAGS=-Wall -Wextra -Werror -pthread -MMD
SRC=	src/main.c \
		src/philosophers.c \
		src/helpers.c
OBJ=$(SRC:.c=.o)
INCLUDE=-Iinclude
%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDE) -c $< -o $@
all: $(NAME)
$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)
clean:
	rm -f $(OBJ)
fclean: clean
	rm -f $(NAME)
re: fclean all
.PHONY: all clean fclean re